### ISSUE TITLE
Save output in the same folder as the input

### ISSUE THREAD

**Issue by Nodraak** [martinber/noaa-apt#14]
Hi!

First of all, thanks a lot for this software, it works well!

The default output folder is `~/`. I think it would make more sense to save the output in the same folder as the input file.

If that sounds reasonable, I can do a PR, I would love to write rust for an OSS project :)

**Comment by martinber** [comment]
I think that it is a good idea. I think that the GUI interface is a bit confusing regarding on where the file is saved (the command-line interface is OK though).

Right now, when saving the decoded file, if the output filename does not indicate an absolute path, the file is saved to the current directory. Current directory can be quite different depending on how the user started noaa-apt, I think that generally is the home directory.

What do you think is the best way to do it? Obviously, if you want, have fun solving it yourself and submit a PR. 

Just in case, here I'm writing two ideas I have right now. 

**One option:**

Write an automatic absolute path to the output filename field when the user selects the input file:

- If the user opens a `/path/to/input/input_file.wav` file, and the *output filename field is empty*. Automatically write as output filename something like `/path/to/input/input_file-decoded.png`
- If the user opens a `/path/to/input/input_file.wav` file, and the *output filename field already has something*. Do nothing, in case that the user already chose an appropiate output filename.

The only problem I see with this method is if some user decodes more than one file. The first time, the output filename is written automatically, but the second time this will not happen, and the previous output will be overwritten if the user is not paying attention. Maybe add a warning when a file is going to be overwritten?

**Another option:**

If the output filename path is relative, save it relative to the input file folder. This is simple and I see no problems with it. Maybe add some tooltip or something, otherwise it wont be clear

**Comment by martinber** [comment]
At the same time we should think about what to do with extensions on output filenames. Windows users usually do not know about extensions (for example the file explorer hides them). So maybe we should add a ".png" extension if the user didn't write one

**Comment by Nodraak** [comment]
Hi again

When opening this issue I thought it would be very easy and quick, but of course it is not so simple!

I thought a bit about your messages, and here are my conclusions (I'm talking only about the GUI version, the CLI do not seems to have a surprising behavior):

* If the output is relative, the file should be saved in the current working directory, as it would be expected for the CLI version (so yeah, I somehow changed my mind!). Nonetheless, I think it would be nice to show the final output filepath near/under the ouput filename widget.
* If the file exists, only show a warning. A modal which require a click is probably annoying both for the user and the dev.
* If no extension, only show a warning (maybe the user intended it. And once again, different behaviour linux vs win is a bad idea imo)

Does that sounds sensible?

**Comment by martinber** [comment]
Hi!

>     * If the output is relative, the file should be saved in the current working directory, as it would be expected for the CLI version (so yeah, I somehow changed my mind!). Nonetheless, I think it would be nice to show the final output filepath near/under the ouput filename widget.

I like that option too

>     * If the file exists, only show a warning. A modal which require a click is probably annoying both for the user and the dev.

I'm not sure how would that work. The warning will be shown while the user is writing the filename? Or when the user clicks Start? 

>     * If no extension, only show a warning (maybe the user intended it. And once again, different behaviour linux vs win is a bad idea imo)

This one is similar to the previous point. If a warning is shown while the user is writing, it can be more annoying than a modal (when writing a filename, initially there is always no extension, and the warning will be shown 100% of the time). Also, what kind of warning? show something on the bottom bar (like when you forget to select an input file)?

I think that instead of warnings, a popup modal asking for "Ok/Cancel" is the best way to solve point 2 and 3. Or maybe I didn't understand what you mean.

**Comment by Nodraak** [comment]
> I'm not sure how would that work. The warning will be shown while the user is writing the filename? Or when the user clicks Start?

My idea was to have a text zone below the output GtkEntry.

For this, and for the extension warning, I think a modal would be anoying... I think it makes more sense to be notified of this earlier, especially since there is a lot of available space.

I have started hacking, see attached screenshot. The warning is show 100% of the time, but in my opinion it is not an issue. I see it more as an "info box", rather than a "scary error".

![Screen1](https://user-images.githubusercontent.com/4773741/75094432-50a49580-558b-11ea-9a70-08dfe1e1ed5a.png)

**Comment by martinber** [comment]
I like it, looks simple enough. I also looked quickly at your code and it looks simple too.

I guess that this is a quick mockup, but anyways, I would do minor changes like removing the exclamation point of the warning and checking the `unwrap()`s. Also, I'd prefer to keep the number of messages as low as we can, for example I think that the "Info: the file does not exist yet, it will be created.\n" message is not necessary.

Thank you very much! Just do a PR when you want
