### ISSUE TITLE
Image data out of sync by ~2px

### ISSUE THREAD

**Issue by Arcadie** [martinber/noaa-apt#26]
I've noticed that the width of the sync band on the final image is around ~2px less than expected (37px instead of 39px). This causes these 2 pixels to end up at the end of each row.

This causes the sync region to "bite into" the minute markers, which in turn overflows into the image data, which overflows into the telemetry data, and so on.

It looks like this:

- Row start, expected band positions in pink:

<img width="524" alt="Screen Shot 2020-08-18 at 22 43 06" src="https://user-images.githubusercontent.com/1472875/90559760-bd00fa00-e1a6-11ea-8584-90c7d8868a88.png">

- Row end, notice how part of the telemetry band (45px) ends up in the channel b image data, and the extra ~2px (black) at the end:

<img width="441" alt="Screen Shot 2020-08-18 at 22 35 15" src="https://user-images.githubusercontent.com/1472875/90560066-37317e80-e1a7-11ea-88c4-3879f9126248.png">

I'm not sure if it's possible to improve accuracy during syncing, and there is a workaround in place when rotating images (as it's only noticeable there), but maybe there is an easy fix for it.

**Comment by martinber** [comment]
Yes, you may be right. The syncing is made in `decode.py:find_sync()`, and I never checked if the syncing was that precise because it was not needed at the time.

I'm going to fix it. Do you have precise numbers of the width of every part? Where did you read that it should be 39px? I'm checking that it makes sense but I wanted to be sure

Also, I'm going to think about [structuring the image data](https://github.com/martinber/noaa-apt/pull/21#issuecomment-669125250)

**Comment by martinber** [comment]
I fixed it, I was wondering if this vertical gray line became wider after the fix, but it looks the same. I think I will leave it

Before:

![image](https://user-images.githubusercontent.com/6921727/90833853-44717900-e31f-11ea-86b0-fe62de0ce773.png)

After:

![image](https://user-images.githubusercontent.com/6921727/90833928-6b2faf80-e31f-11ea-9149-4431afc6eaae.png)
