### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by mgrouch** [martinber/noaa-apt#36]
Error:

thread 'main' panicked at 'Couldn't load resource icon.png: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “./res/icon.png”: No such file or directory" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

(it was built from latest trunk source code)

**Comment by mgrouch** [comment]
If I change runtime directory and fake res/icon.png with something it comes up.

**Comment by martinber** [comment]
The program should be run in a directory containing the [res](https://github.com/martinber/noaa-apt/tree/master/res) folder. It is maybe a bit confusing because when compiling, the program ends up in `target/release/`.

So this is wrong:

```
cargo build --release
cd ./target/release
./noaa-apt
```

And this is the correct way:

```
cargo build --release
./target/release/noaa-apt
```

I don't know what should we do apart from documenting better [here](https://noaa-apt.mbernardi.com.ar/development.html#gnulinux)

**Comment by martinber** [comment]
I think the current behavior is OK. To make things clearer, I added more instructions in the development page of the website. Also I added a `run-noaa-apt.sh` script to allow for easy double-clicking
