### ISSUE TITLE
Command line argivements to change map overlay path

### ISSUE THREAD

**Issue by ghost** [martinber/noaa-apt#37]
While running the GNU/Linux armv7 (no-GUI) on a raspberry pi got the following error.
![image](https://user-images.githubusercontent.com/75289753/103440951-1c503a00-4c70-11eb-9970-cedd3b25e62c.png)

It seems to use a relative path to refer to the res folder. Adding this to the pwd I was able to fix the issue. If it's possible to have a command-line input to change the res location that would solve it. Are there any workarounds for this?

**Comment by martinber** [comment]
Hi. This was intended but I'm realizing that maybe it wasn't a good idea because it is confusing, see that this issue is the same as #36.

The program needs some extra files in the `res/` folder, right now it expects to find it in in the working directory. Instead of providing the location of the folder with an extra argument I would search for the `res/` folder in the location of the executable. See https://doc.rust-lang.org/std/env/fn.current_exe.html . The problem with this is that it can give problems if the user launches the program from a symlink

I don't want to add another argument because I think it would be cumbersome for the user. What do you think?

**Comment by Hasithperera** [comment]
Similar to issue #36 but this lauches the program without any problem. It terminates in the middle only when used with -m "yes". 

I came across this issue trying to schedule a cronjob for decoding. the working directory is set to be the user home in that case.

**Comment by martinber** [comment]
I'm sorry but I will leave it like it is. So when running the program the working directory should have the `res/` folder, which I think it is sort of expected for most software. I think the way is to use something like:

    cd ~/Desktop/noaa-apt/ && ./noaa-apt input.wav -o output.png

I updated the instructions in the website
